# Generated by Django 4.0.5 on 2022-06-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerStoreHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manager_images/')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('money_bank', models.CharField(choices=[('Money', 'Money'), ('Bank', 'Bank')], max_length=32)),
                ('currency_unit', models.CharField(choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outcome_income.outcomecategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
                ('managerStoreHouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outcome_income.managerstorehouse')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('note', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('money_bank', models.CharField(choices=[('Money', 'Money'), ('Bank', 'Bank')], max_length=32)),
                ('currency_unit', models.CharField(choices=[('$', '$'), ('TL', 'TL'), ('SOM', 'SOM'), ('KON', 'KON')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outcome_income.incomecategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
                ('managerStoreHouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outcome_income.managerstorehouse')),
            ],
        ),
    ]
