# Generated by Django 4.0.5 on 2022-06-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='count',
        ),
    ]
