# Generated by Django 4.0.5 on 2022-06-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='count',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
